[build]
  # Directory to run the build command in
  base = "."
  
  # Build command
  command = "npm run build"
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "build"

# Redirect rules for SPA (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
